language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required

branches:
  only:
    - master
    -
before_script:
  - npm install -g @angular/cli

script:
  - ng build diy-tutorials-frontend
  - ng build diy-tutorials-backend
