language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build diy-tutorials-frontend
  - ng build diy-tutorials-backend

before_deploy:
  - tar -zcf diy-tutorials-${TRAVIS_BUILD_NUMBER}.tar.gz ${TRAVIS_BUILD_DIR}/wp-content/plugins/diy-tutorials

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: diy-tutorials-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: false
