language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/


before_script:
  - npm install -g @angular/cli

script:
  - ng build diy-tutorials-frontend
  - ng build diy-tutorials-backend

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/wp-content/plugins/
  - zip -r diy-tutorials-${TRAVIS_BUILD_NUMBER}.zip diy-tutorials

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: diy-tutorials-${TRAVIS_BUILD_NUMBER}.zip
  skip_cleanup: true
  on:
    tags: true
